#############################################################################
# Makefile for building: armsim
# Generated by qmake (3.1) (Qt 5.11.1)
# Project:  armsim.pro
# Template: subdirs
# Command: C:\Qt\5.11.1\msvc2017_64\bin\qmake.exe -o Makefile armsim.pro -config release
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = C:\Qt\5.11.1\msvc2017_64\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = C:\Qt\5.11.1\msvc2017_64\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = C:\Qt\5.11.1\msvc2017_64\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		sub-armsim \
		sub-ramtests \
		sub-loadertests


sub-armsim-qmake_all:  FORCE
	@if not exist armsim\ mkdir armsim\ & if not exist armsim\ exit 1
	cd armsim\ && $(QMAKE) -o Makefile "C:\Users\benja\OneDrive\Documents\School\Microprocessor Architecture\Loader\armsim\armsim\armsim.pro" -config release
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd armsim\ && $(MAKE) -f Makefile qmake_all
sub-armsim: FORCE
	@if not exist armsim\ mkdir armsim\ & if not exist armsim\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd armsim\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\benja\OneDrive\Documents\School\Microprocessor Architecture\Loader\armsim\armsim\armsim.pro" -config release ) && $(MAKE) -f Makefile
sub-armsim-make_first-ordered: FORCE
	@if not exist armsim\ mkdir armsim\ & if not exist armsim\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd armsim\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\benja\OneDrive\Documents\School\Microprocessor Architecture\Loader\armsim\armsim\armsim.pro" -config release ) && $(MAKE) -f Makefile 
sub-armsim-make_first: FORCE
	@if not exist armsim\ mkdir armsim\ & if not exist armsim\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd armsim\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\benja\OneDrive\Documents\School\Microprocessor Architecture\Loader\armsim\armsim\armsim.pro" -config release ) && $(MAKE) -f Makefile 
sub-armsim-all-ordered: FORCE
	@if not exist armsim\ mkdir armsim\ & if not exist armsim\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd armsim\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\benja\OneDrive\Documents\School\Microprocessor Architecture\Loader\armsim\armsim\armsim.pro" -config release ) && $(MAKE) -f Makefile all
sub-armsim-all: FORCE
	@if not exist armsim\ mkdir armsim\ & if not exist armsim\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd armsim\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\benja\OneDrive\Documents\School\Microprocessor Architecture\Loader\armsim\armsim\armsim.pro" -config release ) && $(MAKE) -f Makefile all
sub-armsim-clean-ordered: FORCE
	@if not exist armsim\ mkdir armsim\ & if not exist armsim\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd armsim\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\benja\OneDrive\Documents\School\Microprocessor Architecture\Loader\armsim\armsim\armsim.pro" -config release ) && $(MAKE) -f Makefile clean
sub-armsim-clean: FORCE
	@if not exist armsim\ mkdir armsim\ & if not exist armsim\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd armsim\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\benja\OneDrive\Documents\School\Microprocessor Architecture\Loader\armsim\armsim\armsim.pro" -config release ) && $(MAKE) -f Makefile clean
sub-armsim-distclean-ordered: FORCE
	@if not exist armsim\ mkdir armsim\ & if not exist armsim\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd armsim\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\benja\OneDrive\Documents\School\Microprocessor Architecture\Loader\armsim\armsim\armsim.pro" -config release ) && $(MAKE) -f Makefile distclean
sub-armsim-distclean: FORCE
	@if not exist armsim\ mkdir armsim\ & if not exist armsim\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd armsim\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\benja\OneDrive\Documents\School\Microprocessor Architecture\Loader\armsim\armsim\armsim.pro" -config release ) && $(MAKE) -f Makefile distclean
sub-armsim-install_subtargets-ordered: FORCE
	@if not exist armsim\ mkdir armsim\ & if not exist armsim\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd armsim\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\benja\OneDrive\Documents\School\Microprocessor Architecture\Loader\armsim\armsim\armsim.pro" -config release ) && $(MAKE) -f Makefile install
sub-armsim-install_subtargets: FORCE
	@if not exist armsim\ mkdir armsim\ & if not exist armsim\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd armsim\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\benja\OneDrive\Documents\School\Microprocessor Architecture\Loader\armsim\armsim\armsim.pro" -config release ) && $(MAKE) -f Makefile install
sub-armsim-uninstall_subtargets-ordered: FORCE
	@if not exist armsim\ mkdir armsim\ & if not exist armsim\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd armsim\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\benja\OneDrive\Documents\School\Microprocessor Architecture\Loader\armsim\armsim\armsim.pro" -config release ) && $(MAKE) -f Makefile uninstall
sub-armsim-uninstall_subtargets: FORCE
	@if not exist armsim\ mkdir armsim\ & if not exist armsim\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd armsim\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\benja\OneDrive\Documents\School\Microprocessor Architecture\Loader\armsim\armsim\armsim.pro" -config release ) && $(MAKE) -f Makefile uninstall
sub-ramtests-qmake_all: sub-armsim-qmake_all FORCE
	@if not exist ramtests\ mkdir ramtests\ & if not exist ramtests\ exit 1
	cd ramtests\ && $(QMAKE) -o Makefile "C:\Users\benja\OneDrive\Documents\School\Microprocessor Architecture\Loader\armsim\ramtests\ramtests.pro" -config release
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ramtests\ && $(MAKE) -f Makefile qmake_all
sub-ramtests: FORCE
	@if not exist ramtests\ mkdir ramtests\ & if not exist ramtests\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ramtests\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\benja\OneDrive\Documents\School\Microprocessor Architecture\Loader\armsim\ramtests\ramtests.pro" -config release ) && $(MAKE) -f Makefile
sub-ramtests-make_first-ordered: sub-armsim-make_first-ordered  FORCE
	@if not exist ramtests\ mkdir ramtests\ & if not exist ramtests\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ramtests\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\benja\OneDrive\Documents\School\Microprocessor Architecture\Loader\armsim\ramtests\ramtests.pro" -config release ) && $(MAKE) -f Makefile 
sub-ramtests-make_first: FORCE
	@if not exist ramtests\ mkdir ramtests\ & if not exist ramtests\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ramtests\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\benja\OneDrive\Documents\School\Microprocessor Architecture\Loader\armsim\ramtests\ramtests.pro" -config release ) && $(MAKE) -f Makefile 
sub-ramtests-all-ordered: sub-armsim-all-ordered  FORCE
	@if not exist ramtests\ mkdir ramtests\ & if not exist ramtests\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ramtests\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\benja\OneDrive\Documents\School\Microprocessor Architecture\Loader\armsim\ramtests\ramtests.pro" -config release ) && $(MAKE) -f Makefile all
sub-ramtests-all: FORCE
	@if not exist ramtests\ mkdir ramtests\ & if not exist ramtests\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ramtests\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\benja\OneDrive\Documents\School\Microprocessor Architecture\Loader\armsim\ramtests\ramtests.pro" -config release ) && $(MAKE) -f Makefile all
sub-ramtests-clean-ordered: sub-armsim-clean-ordered  FORCE
	@if not exist ramtests\ mkdir ramtests\ & if not exist ramtests\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ramtests\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\benja\OneDrive\Documents\School\Microprocessor Architecture\Loader\armsim\ramtests\ramtests.pro" -config release ) && $(MAKE) -f Makefile clean
sub-ramtests-clean: FORCE
	@if not exist ramtests\ mkdir ramtests\ & if not exist ramtests\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ramtests\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\benja\OneDrive\Documents\School\Microprocessor Architecture\Loader\armsim\ramtests\ramtests.pro" -config release ) && $(MAKE) -f Makefile clean
sub-ramtests-distclean-ordered: sub-armsim-distclean-ordered  FORCE
	@if not exist ramtests\ mkdir ramtests\ & if not exist ramtests\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ramtests\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\benja\OneDrive\Documents\School\Microprocessor Architecture\Loader\armsim\ramtests\ramtests.pro" -config release ) && $(MAKE) -f Makefile distclean
sub-ramtests-distclean: FORCE
	@if not exist ramtests\ mkdir ramtests\ & if not exist ramtests\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ramtests\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\benja\OneDrive\Documents\School\Microprocessor Architecture\Loader\armsim\ramtests\ramtests.pro" -config release ) && $(MAKE) -f Makefile distclean
sub-ramtests-install_subtargets-ordered: sub-armsim-install_subtargets-ordered  FORCE
	@if not exist ramtests\ mkdir ramtests\ & if not exist ramtests\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ramtests\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\benja\OneDrive\Documents\School\Microprocessor Architecture\Loader\armsim\ramtests\ramtests.pro" -config release ) && $(MAKE) -f Makefile install
sub-ramtests-install_subtargets: FORCE
	@if not exist ramtests\ mkdir ramtests\ & if not exist ramtests\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ramtests\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\benja\OneDrive\Documents\School\Microprocessor Architecture\Loader\armsim\ramtests\ramtests.pro" -config release ) && $(MAKE) -f Makefile install
sub-ramtests-uninstall_subtargets-ordered: sub-armsim-uninstall_subtargets-ordered  FORCE
	@if not exist ramtests\ mkdir ramtests\ & if not exist ramtests\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ramtests\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\benja\OneDrive\Documents\School\Microprocessor Architecture\Loader\armsim\ramtests\ramtests.pro" -config release ) && $(MAKE) -f Makefile uninstall
sub-ramtests-uninstall_subtargets: FORCE
	@if not exist ramtests\ mkdir ramtests\ & if not exist ramtests\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ramtests\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\benja\OneDrive\Documents\School\Microprocessor Architecture\Loader\armsim\ramtests\ramtests.pro" -config release ) && $(MAKE) -f Makefile uninstall
sub-loadertests-qmake_all: sub-ramtests-qmake_all FORCE
	@if not exist loadertests\ mkdir loadertests\ & if not exist loadertests\ exit 1
	cd loadertests\ && $(QMAKE) -o Makefile "C:\Users\benja\OneDrive\Documents\School\Microprocessor Architecture\Loader\armsim\loadertests\loadertests.pro" -config release
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd loadertests\ && $(MAKE) -f Makefile qmake_all
sub-loadertests: FORCE
	@if not exist loadertests\ mkdir loadertests\ & if not exist loadertests\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd loadertests\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\benja\OneDrive\Documents\School\Microprocessor Architecture\Loader\armsim\loadertests\loadertests.pro" -config release ) && $(MAKE) -f Makefile
sub-loadertests-make_first-ordered: sub-ramtests-make_first-ordered  FORCE
	@if not exist loadertests\ mkdir loadertests\ & if not exist loadertests\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd loadertests\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\benja\OneDrive\Documents\School\Microprocessor Architecture\Loader\armsim\loadertests\loadertests.pro" -config release ) && $(MAKE) -f Makefile 
sub-loadertests-make_first: FORCE
	@if not exist loadertests\ mkdir loadertests\ & if not exist loadertests\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd loadertests\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\benja\OneDrive\Documents\School\Microprocessor Architecture\Loader\armsim\loadertests\loadertests.pro" -config release ) && $(MAKE) -f Makefile 
sub-loadertests-all-ordered: sub-ramtests-all-ordered  FORCE
	@if not exist loadertests\ mkdir loadertests\ & if not exist loadertests\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd loadertests\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\benja\OneDrive\Documents\School\Microprocessor Architecture\Loader\armsim\loadertests\loadertests.pro" -config release ) && $(MAKE) -f Makefile all
sub-loadertests-all: FORCE
	@if not exist loadertests\ mkdir loadertests\ & if not exist loadertests\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd loadertests\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\benja\OneDrive\Documents\School\Microprocessor Architecture\Loader\armsim\loadertests\loadertests.pro" -config release ) && $(MAKE) -f Makefile all
sub-loadertests-clean-ordered: sub-ramtests-clean-ordered  FORCE
	@if not exist loadertests\ mkdir loadertests\ & if not exist loadertests\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd loadertests\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\benja\OneDrive\Documents\School\Microprocessor Architecture\Loader\armsim\loadertests\loadertests.pro" -config release ) && $(MAKE) -f Makefile clean
sub-loadertests-clean: FORCE
	@if not exist loadertests\ mkdir loadertests\ & if not exist loadertests\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd loadertests\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\benja\OneDrive\Documents\School\Microprocessor Architecture\Loader\armsim\loadertests\loadertests.pro" -config release ) && $(MAKE) -f Makefile clean
sub-loadertests-distclean-ordered: sub-ramtests-distclean-ordered  FORCE
	@if not exist loadertests\ mkdir loadertests\ & if not exist loadertests\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd loadertests\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\benja\OneDrive\Documents\School\Microprocessor Architecture\Loader\armsim\loadertests\loadertests.pro" -config release ) && $(MAKE) -f Makefile distclean
sub-loadertests-distclean: FORCE
	@if not exist loadertests\ mkdir loadertests\ & if not exist loadertests\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd loadertests\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\benja\OneDrive\Documents\School\Microprocessor Architecture\Loader\armsim\loadertests\loadertests.pro" -config release ) && $(MAKE) -f Makefile distclean
sub-loadertests-install_subtargets-ordered: sub-ramtests-install_subtargets-ordered  FORCE
	@if not exist loadertests\ mkdir loadertests\ & if not exist loadertests\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd loadertests\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\benja\OneDrive\Documents\School\Microprocessor Architecture\Loader\armsim\loadertests\loadertests.pro" -config release ) && $(MAKE) -f Makefile install
sub-loadertests-install_subtargets: FORCE
	@if not exist loadertests\ mkdir loadertests\ & if not exist loadertests\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd loadertests\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\benja\OneDrive\Documents\School\Microprocessor Architecture\Loader\armsim\loadertests\loadertests.pro" -config release ) && $(MAKE) -f Makefile install
sub-loadertests-uninstall_subtargets-ordered: sub-ramtests-uninstall_subtargets-ordered  FORCE
	@if not exist loadertests\ mkdir loadertests\ & if not exist loadertests\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd loadertests\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\benja\OneDrive\Documents\School\Microprocessor Architecture\Loader\armsim\loadertests\loadertests.pro" -config release ) && $(MAKE) -f Makefile uninstall
sub-loadertests-uninstall_subtargets: FORCE
	@if not exist loadertests\ mkdir loadertests\ & if not exist loadertests\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd loadertests\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\benja\OneDrive\Documents\School\Microprocessor Architecture\Loader\armsim\loadertests\loadertests.pro" -config release ) && $(MAKE) -f Makefile uninstall

Makefile: armsim.pro C:\Qt\5.11.1\msvc2017_64\mkspecs\win32-msvc\qmake.conf C:\Qt\5.11.1\msvc2017_64\mkspecs\features\spec_pre.prf \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\common\angle.conf \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\common\windows-vulkan.conf \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\common\msvc-desktop.conf \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\qconfig.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_3danimation.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_3danimation_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_3dcore.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_3dcore_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_3dextras.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_3dextras_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_3dinput.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_3dinput_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_3dlogic.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_3dlogic_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_3dquick.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_3dquick_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_3dquickanimation.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_3dquickanimation_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_3dquickextras.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_3dquickextras_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_3dquickinput.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_3dquickinput_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_3dquickrender.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_3dquickrender_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_3dquickscene2d.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_3dquickscene2d_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_3drender.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_3drender_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_accessibility_support_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_axbase.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_axbase_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_axcontainer.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_axcontainer_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_axserver.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_axserver_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_bluetooth.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_bluetooth_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_bootstrap_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_charts.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_charts_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_concurrent.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_concurrent_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_core.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_core_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_datavisualization.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_datavisualization_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_dbus.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_dbus_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_designer.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_designer_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_designercomponents_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_devicediscovery_support_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_edid_support_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_egl_support_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_fb_support_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_fontdatabase_support_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_gamepad.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_gamepad_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_gui.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_gui_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_help.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_help_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_location.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_location_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_multimedia.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_multimedia_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_multimediawidgets.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_network.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_network_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_networkauth.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_networkauth_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_nfc.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_nfc_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_opengl.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_opengl_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_openglextensions.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_openglextensions_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_packetprotocol_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_platformcompositor_support_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_positioning.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_positioning_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_positioningquick.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_positioningquick_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_printsupport.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_printsupport_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_purchasing.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_purchasing_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_qml.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_qml_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_qmldebug_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_qmltest.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_qmltest_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_quick.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_quick_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_quickcontrols2.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_quickparticles_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_quickwidgets.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_remoteobjects.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_remoteobjects_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_repparser.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_repparser_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_scxml.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_scxml_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_sensors.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_sensors_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_serialbus.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_serialbus_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_serialport.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_serialport_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_sql.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_sql_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_svg.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_svg_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_testlib.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_testlib_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_texttospeech.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_texttospeech_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_theme_support_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_uiplugin.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_uitools.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_uitools_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_vulkan_support_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_webchannel.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_webchannel_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_webengine.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_webengine_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_webenginecore.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_webenginecore_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_webenginecoreheaders_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_webenginewidgets.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_webenginewidgets_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_websockets.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_websockets_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_webview.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_webview_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_widgets.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_widgets_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_windowsuiautomation_support_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_winextras.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_winextras_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_xml.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_xml_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_xmlpatterns.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_zlib_private.pri \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\features\qt_functions.prf \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\features\qt_config.prf \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\win32-msvc\qmake.conf \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\features\spec_post.prf \
		.qmake.stash \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\features\exclusive_builds.prf \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\common\msvc-version.conf \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\features\toolchain.prf \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\features\default_pre.prf \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\features\win32\default_pre.prf \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\features\resolve_config.prf \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\features\exclusive_builds_post.prf \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\features\default_post.prf \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\features\precompile_header.prf \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\features\warn_on.prf \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\features\qmake_use.prf \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\features\file_copies.prf \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\features\win32\windows.prf \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\features\testcase_targets.prf \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\features\exceptions.prf \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\features\yacc.prf \
		C:\Qt\5.11.1\msvc2017_64\mkspecs\features\lex.prf \
		armsim.pro
	$(QMAKE) -o Makefile armsim.pro -config release
C:\Qt\5.11.1\msvc2017_64\mkspecs\features\spec_pre.prf:
C:\Qt\5.11.1\msvc2017_64\mkspecs\common\angle.conf:
C:\Qt\5.11.1\msvc2017_64\mkspecs\common\windows-vulkan.conf:
C:\Qt\5.11.1\msvc2017_64\mkspecs\common\msvc-desktop.conf:
C:\Qt\5.11.1\msvc2017_64\mkspecs\qconfig.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_3danimation.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_3danimation_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_3dcore.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_3dcore_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_3dextras.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_3dextras_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_3dinput.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_3dinput_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_3dlogic.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_3dlogic_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_3dquick.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_3dquick_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_3dquickanimation.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_3dquickanimation_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_3dquickextras.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_3dquickextras_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_3dquickinput.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_3dquickinput_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_3dquickrender.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_3dquickrender_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_3dquickscene2d.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_3dquickscene2d_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_3drender.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_3drender_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_accessibility_support_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_axbase.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_axbase_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_axcontainer.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_axcontainer_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_axserver.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_axserver_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_bluetooth.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_bluetooth_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_bootstrap_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_charts.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_charts_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_concurrent.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_concurrent_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_core.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_core_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_datavisualization.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_datavisualization_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_dbus.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_dbus_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_designer.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_designer_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_designercomponents_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_devicediscovery_support_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_edid_support_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_egl_support_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_fb_support_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_fontdatabase_support_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_gamepad.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_gamepad_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_gui.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_gui_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_help.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_help_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_location.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_location_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_multimedia.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_multimedia_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_multimediawidgets.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_network.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_network_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_networkauth.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_networkauth_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_nfc.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_nfc_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_opengl.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_opengl_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_openglextensions.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_openglextensions_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_packetprotocol_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_platformcompositor_support_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_positioning.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_positioning_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_positioningquick.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_positioningquick_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_printsupport.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_printsupport_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_purchasing.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_purchasing_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_qml.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_qml_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_qmldebug_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_qmldevtools_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_qmltest.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_qmltest_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_quick.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_quick_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_quickcontrols2.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_quickparticles_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_quickwidgets.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_quickwidgets_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_remoteobjects.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_remoteobjects_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_repparser.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_repparser_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_scxml.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_scxml_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_sensors.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_sensors_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_serialbus.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_serialbus_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_serialport.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_serialport_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_sql.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_sql_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_svg.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_svg_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_testlib.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_testlib_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_texttospeech.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_texttospeech_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_theme_support_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_uiplugin.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_uitools.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_uitools_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_vulkan_support_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_webchannel.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_webchannel_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_webengine.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_webengine_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_webenginecore.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_webenginecore_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_webenginecoreheaders_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_webenginewidgets.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_webenginewidgets_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_websockets.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_websockets_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_webview.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_webview_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_widgets.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_widgets_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_windowsuiautomation_support_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_winextras.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_winextras_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_xml.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_xml_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_xmlpatterns.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\modules\qt_lib_zlib_private.pri:
C:\Qt\5.11.1\msvc2017_64\mkspecs\features\qt_functions.prf:
C:\Qt\5.11.1\msvc2017_64\mkspecs\features\qt_config.prf:
C:\Qt\5.11.1\msvc2017_64\mkspecs\win32-msvc\qmake.conf:
C:\Qt\5.11.1\msvc2017_64\mkspecs\features\spec_post.prf:
.qmake.stash:
C:\Qt\5.11.1\msvc2017_64\mkspecs\features\exclusive_builds.prf:
C:\Qt\5.11.1\msvc2017_64\mkspecs\common\msvc-version.conf:
C:\Qt\5.11.1\msvc2017_64\mkspecs\features\toolchain.prf:
C:\Qt\5.11.1\msvc2017_64\mkspecs\features\default_pre.prf:
C:\Qt\5.11.1\msvc2017_64\mkspecs\features\win32\default_pre.prf:
C:\Qt\5.11.1\msvc2017_64\mkspecs\features\resolve_config.prf:
C:\Qt\5.11.1\msvc2017_64\mkspecs\features\exclusive_builds_post.prf:
C:\Qt\5.11.1\msvc2017_64\mkspecs\features\default_post.prf:
C:\Qt\5.11.1\msvc2017_64\mkspecs\features\precompile_header.prf:
C:\Qt\5.11.1\msvc2017_64\mkspecs\features\warn_on.prf:
C:\Qt\5.11.1\msvc2017_64\mkspecs\features\qmake_use.prf:
C:\Qt\5.11.1\msvc2017_64\mkspecs\features\file_copies.prf:
C:\Qt\5.11.1\msvc2017_64\mkspecs\features\win32\windows.prf:
C:\Qt\5.11.1\msvc2017_64\mkspecs\features\testcase_targets.prf:
C:\Qt\5.11.1\msvc2017_64\mkspecs\features\exceptions.prf:
C:\Qt\5.11.1\msvc2017_64\mkspecs\features\yacc.prf:
C:\Qt\5.11.1\msvc2017_64\mkspecs\features\lex.prf:
armsim.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile armsim.pro -config release

qmake_all: sub-armsim-qmake_all sub-ramtests-qmake_all sub-loadertests-qmake_all FORCE

make_first: sub-armsim-make_first-ordered sub-ramtests-make_first-ordered sub-loadertests-make_first-ordered  FORCE
all: sub-armsim-all-ordered sub-ramtests-all-ordered sub-loadertests-all-ordered  FORCE
clean: sub-armsim-clean-ordered sub-ramtests-clean-ordered sub-loadertests-clean-ordered  FORCE
distclean: sub-armsim-distclean-ordered sub-ramtests-distclean-ordered sub-loadertests-distclean-ordered  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-armsim-install_subtargets-ordered sub-ramtests-install_subtargets-ordered sub-loadertests-install_subtargets-ordered FORCE
uninstall_subtargets: sub-armsim-uninstall_subtargets-ordered sub-ramtests-uninstall_subtargets-ordered sub-loadertests-uninstall_subtargets-ordered FORCE

sub-armsim-debug_ordered:
	@if not exist armsim\ mkdir armsim\ & if not exist armsim\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd armsim\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\benja\OneDrive\Documents\School\Microprocessor Architecture\Loader\armsim\armsim\armsim.pro" -config release ) && $(MAKE) -f Makefile debug
sub-ramtests-debug_ordered: sub-armsim-debug_ordered 
	@if not exist ramtests\ mkdir ramtests\ & if not exist ramtests\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ramtests\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\benja\OneDrive\Documents\School\Microprocessor Architecture\Loader\armsim\ramtests\ramtests.pro" -config release ) && $(MAKE) -f Makefile debug
sub-loadertests-debug_ordered: sub-ramtests-debug_ordered 
	@if not exist loadertests\ mkdir loadertests\ & if not exist loadertests\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd loadertests\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\benja\OneDrive\Documents\School\Microprocessor Architecture\Loader\armsim\loadertests\loadertests.pro" -config release ) && $(MAKE) -f Makefile debug
debug: sub-armsim-debug_ordered sub-ramtests-debug_ordered sub-loadertests-debug_ordered

sub-armsim-release_ordered:
	@if not exist armsim\ mkdir armsim\ & if not exist armsim\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd armsim\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\benja\OneDrive\Documents\School\Microprocessor Architecture\Loader\armsim\armsim\armsim.pro" -config release ) && $(MAKE) -f Makefile release
sub-ramtests-release_ordered: sub-armsim-release_ordered 
	@if not exist ramtests\ mkdir ramtests\ & if not exist ramtests\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ramtests\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\benja\OneDrive\Documents\School\Microprocessor Architecture\Loader\armsim\ramtests\ramtests.pro" -config release ) && $(MAKE) -f Makefile release
sub-loadertests-release_ordered: sub-ramtests-release_ordered 
	@if not exist loadertests\ mkdir loadertests\ & if not exist loadertests\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd loadertests\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\benja\OneDrive\Documents\School\Microprocessor Architecture\Loader\armsim\loadertests\loadertests.pro" -config release ) && $(MAKE) -f Makefile release
release: sub-armsim-release_ordered sub-ramtests-release_ordered sub-loadertests-release_ordered

sub-armsim-check_ordered:
	@if not exist armsim\ mkdir armsim\ & if not exist armsim\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd armsim\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\benja\OneDrive\Documents\School\Microprocessor Architecture\Loader\armsim\armsim\armsim.pro" -config release ) && $(MAKE) -f Makefile check
sub-ramtests-check_ordered: sub-armsim-check_ordered 
	@if not exist ramtests\ mkdir ramtests\ & if not exist ramtests\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ramtests\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\benja\OneDrive\Documents\School\Microprocessor Architecture\Loader\armsim\ramtests\ramtests.pro" -config release ) && $(MAKE) -f Makefile check
sub-loadertests-check_ordered: sub-ramtests-check_ordered 
	@if not exist loadertests\ mkdir loadertests\ & if not exist loadertests\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd loadertests\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\benja\OneDrive\Documents\School\Microprocessor Architecture\Loader\armsim\loadertests\loadertests.pro" -config release ) && $(MAKE) -f Makefile check
check: sub-armsim-check_ordered sub-ramtests-check_ordered sub-loadertests-check_ordered

sub-armsim-benchmark_ordered:
	@if not exist armsim\ mkdir armsim\ & if not exist armsim\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd armsim\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\benja\OneDrive\Documents\School\Microprocessor Architecture\Loader\armsim\armsim\armsim.pro" -config release ) && $(MAKE) -f Makefile benchmark
sub-ramtests-benchmark_ordered: sub-armsim-benchmark_ordered 
	@if not exist ramtests\ mkdir ramtests\ & if not exist ramtests\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ramtests\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\benja\OneDrive\Documents\School\Microprocessor Architecture\Loader\armsim\ramtests\ramtests.pro" -config release ) && $(MAKE) -f Makefile benchmark
sub-loadertests-benchmark_ordered: sub-ramtests-benchmark_ordered 
	@if not exist loadertests\ mkdir loadertests\ & if not exist loadertests\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd loadertests\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\benja\OneDrive\Documents\School\Microprocessor Architecture\Loader\armsim\loadertests\loadertests.pro" -config release ) && $(MAKE) -f Makefile benchmark
benchmark: sub-armsim-benchmark_ordered sub-ramtests-benchmark_ordered sub-loadertests-benchmark_ordered
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

